added linkcode_resolve
unifyai/doc-builder pull request #23
Opened 2023-07-04 12:34 UTC by selvaraj-sembulingam

Changed _sphinx.ext.viewcode_ to _sphinx.ext.linkcode_

2023-07-05 13:41 UTC, KareemMAX requested changes
Hey @selvaraj-sembulingam, great work 🚀🚀🚀

I have some comments on how the code is structured that I would like you to fix before we merge. Also the support of different module names.

2023-07-05 17:58 UTC, selvaraj-sembulingam commented on docs/conf.py
> +    submod = sys.modules.get(modname)
Done

2023-07-05 17:58 UTC, selvaraj-sembulingam commented on docs/conf.py
> +    obj = submod
Removed

2023-07-05 17:58 UTC, selvaraj-sembulingam commented on docs/conf.py
> +    if fn is None:
Removed

2023-07-05 17:58 UTC, selvaraj-sembulingam commented on docs/conf.py
> +        linespec = ""
Done

2023-07-05 17:59 UTC, selvaraj-sembulingam commented on docs/conf.py
> +    return github_url
Done

2023-07-05 17:59 UTC, selvaraj-sembulingam commented on docs/conf.py
> +            return None
Yeah Done

2023-07-06 13:20 UTC, KareemMAX commented on docs/conf.py
> +        linespec = "#L%d-L%d" % (lineno, lineno + len(source) - 1)
Don't you think that might return an exception in case of `lineno` is `None`?

2023-07-06 13:20 UTC, KareemMAX commented on docs/conf.py
> +        linespec = "#L%d-L%d" % (lineno, lineno + len(source) - 1)
```suggestion
    linespec = ""

    if lineno:
        linespec = "#L%d-L%d" % (lineno, lineno + len(source) - 1)
```

2023-07-06 13:20 UTC, KareemMAX commented on docs/conf.py
> +    fn = os.path.relpath(fn, start=os.path.dirname(__import__("ivy").__file__))
I'm not really sure if we should be that coupled to the naming convention. Wouldn't it be better if we got `repo_name` from the partial config?

2023-07-06 13:40 UTC, KareemMAX requested changes
Awesome work, please address my changes and then we are good to go

2023-07-06 15:32 UTC, selvaraj-sembulingam commented on docs/conf.py
> +    fn = os.path.relpath(fn, start=os.path.dirname(__import__("ivy").__file__))
Sure

2023-07-10 13:55 UTC, merged